schema:
  - ./schema.graphqls
exec:
  filename: internal/generated/exec.go
  package: generated
  layout: follow-schema
  dir: internal/generated
model:
  filename: internal/models/generated.go
  package: models

resolver:
  layout: follow-schema
  dir: pkg/graphlql
  package: graphql
  filename_template: "{name}.resolvers.go"

